FILE(GLOB files "${CMAKE_CURRENT_SOURCE_DIR}/share/icons/*.png")

INSTALL(FILES   ${CMAKE_CURRENT_SOURCE_DIR}/AUTHORS
				${CMAKE_CURRENT_SOURCE_DIR}/COPYING
				${CMAKE_CURRENT_SOURCE_DIR}/VERSION
				
	DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/share)
  
INSTALL(FILES ${files}
		DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/share/icons)
	
#~ 
#~ INSTALL(PROGRAMS ${CMAKE_CURRENT_BINARY_DIR}/TwitCrusader-1.0.0
  #~ DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/bin)

INSTALL(TARGETS ${CMAKE_CURRENT_BINARY_DIR}/bin/TwitCrusader 
				${CMAKE_CURRENT_BINARY_DIR}/dependences/liblogc.a
				${CMAKE_CURRENT_BINARY_DIR}/dependences/libtwitc.a
  RUNTIME DESTINATION bin
  LIBRARY DESTINATION lib
)
