Document: twitcrusader
Title: Debian twitcrusader Manual
Author: <insert document author here>
Abstract: This manual describes what twitcrusader is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/twitcrusader/twitcrusader.sgml.gz

Format: postscript
Files: /usr/share/doc/twitcrusader/twitcrusader.ps.gz

Format: text
Files: /usr/share/doc/twitcrusader/twitcrusader.text.gz

Format: HTML
Index: /usr/share/doc/twitcrusader/html/index.html
Files: /usr/share/doc/twitcrusader/html/*.html
